---
# custom image details
name: ublue-silverblue
description: Custom Universal Blue Silverblue image by BlastPKMN

# base image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

# module configuration, executed in order
modules:
  
  - type: script
    
    # run scripts
    scripts:
    
      - kernel-cachyos.sh

  - type: dnf
        
    # install packages    
    install:
    
      packages:
      
        - fastfetch
        - fish
        
    # remove packages
    remove:
      
      packages:
        
        - nvtop
        - htop
        - firefox
        - firefox-langpacks
        - malcontent-control
        - mediawriter
        - gnome-calculator
        - gnome-calendar
        - gnome-characters
        - gnome-clocks
        - gnome-connections
        - gnome-contacts
        - gnome-font-viewer
        - yelp
        - gnome-maps
        - papers
        - snapshot
        - gnome-tour
        - gnome-weather

  # this sets up the proper policy and signing files for signed images to work fully
  - type: signing
