---
# custom image details
name: ublue-silverblue
description: Custom Universal Blue Silverblue image by BlastPKMN

# base image
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 44

# module configuration, executed in order
modules:
  
  - type: script
    
    # run scripts
    scripts:
    
      - kernel-cachyos.sh

  - type: dnf
    
    # install packages    
    install:
    
      packages:
      
        - fastfetch
        - fish
        - gdm-settings
        
    # remove packages
    remove:
      
      packages:
        
        - firefox
        - firefox-langpacks
        - gnome-disk-utility
        - gnome-software
        - gnome-system-monitor
        - gnome-tour
        - htop
        - malcontent-control
        - nvtop
        - yelp

  # this sets up the proper policy and signing files for signed images to work fully
  - type: signing
